# Compilation settings 
STD = -std=c++17
FLAGS = -Wall -Wextra
GCC = g++ $(STD) $(FLAGS)
OUT = -o generator 
# Files to compile 
# INCLUDE = 
 
MAIN = main.cpp  
SRC = $(MAIN) 
FILES = $(SRC)

# Rules 
all: main 

main:  $(FILES)
	$(GCC) $(SRC) $(OUT) 

